export type ZoneType = "Body Construction" | "Paint" | "Final Assembly";
export type HealthStatus = "online" | "warning" | "critical";
export type InstrumentationLevel = "Full" | "Partial" | "Manual";

export interface StationSensorMetric {
  name: string;
  value: string;
  baseline: string;
  unit: string;
  isNominal: boolean;
}

export interface StationItem {
  id: number;
  stationNumber: number;
  name: string;
  code: string;
  zone: ZoneType;
  orbitRing: 1 | 2 | 3; // 1 = Body Construction, 2 = Paint, 3 = Final Assembly
  health: HealthStatus;
  instrumentation: InstrumentationLevel;
  instrumentationDetails: string;
  description: string;
  riskScore: number; // 0 - 100%
  sensors?: StationSensorMetric[];
  sparklineHistory?: number[]; // 8-10 points
  predictedImpact?: string;
  nextMaintenance: string;
  manualLog?: string; // If instrumentation is Manual
  upstreamIds: number[];
  downstreamIds: number[];
}

export const productionStations: StationItem[] = [
  // INNER RING (1): Body Construction (6 Stations, ST-01 to ST-06)
  {
    id: 1,
    stationNumber: 1,
    name: "Underbody Framing",
    code: "ST-01-UB",
    zone: "Body Construction",
    orbitRing: 1,
    health: "online",
    instrumentation: "Full",
    instrumentationDetails: "Full — Torque, Clamp Pressure, Vibration",
    description: "Multi-point automated clamping fixtures align and secure high-strength steel chassis baseplate.",
    riskScore: 14,
    sensors: [
      { name: "Clamp Pressure", value: "24.2", baseline: "24.0", unit: "bar", isNominal: true },
      { name: "Torque", value: "148", baseline: "150", unit: "Nm", isNominal: true },
    ],
    sparklineHistory: [12, 14, 15, 14, 13, 14, 15, 14],
    predictedImpact: "Nominal — no downstream variance predicted",
    nextMaintenance: "In 72 hrs (Cycle #18,400)",
    upstreamIds: [],
    downstreamIds: [2, 3],
  },
  {
    id: 2,
    stationNumber: 2,
    name: "Side Aperture Hemming",
    code: "ST-02-SA",
    zone: "Body Construction",
    orbitRing: 1,
    health: "online",
    instrumentation: "Full",
    instrumentationDetails: "Full — Roller Force, Temp, Positioning",
    description: "Robotic roller hemming forms flush B-pillar edges and reinforced door opening flanges.",
    riskScore: 22,
    sensors: [
      { name: "Roller Force", value: "8.6", baseline: "8.5", unit: "kN", isNominal: true },
      { name: "Tool Temp", value: "54", baseline: "52", unit: "°C", isNominal: true },
    ],
    sparklineHistory: [18, 20, 24, 22, 21, 23, 22, 22],
    predictedImpact: "Flange clearance nominal within ±0.03mm",
    nextMaintenance: "In 96 hrs (Cycle #22,100)",
    upstreamIds: [1],
    downstreamIds: [3, 4],
  },
  {
    id: 3,
    stationNumber: 3,
    name: "Roof Laser Seam Weld",
    code: "ST-03-LW",
    zone: "Body Construction",
    orbitRing: 1,
    health: "warning",
    instrumentation: "Full",
    instrumentationDetails: "Full — Laser Power, Focal Offset, Optics Temp",
    description: "Fiber laser optics braze continuous roof ditch seam with zero-spatter automated trajectory.",
    riskScore: 58,
    sensors: [
      { name: "Laser Power", value: "4.8", baseline: "4.2", unit: "kW", isNominal: false },
      { name: "Focal Offset", value: "+0.18", baseline: "0.00", unit: "mm", isNominal: false },
      { name: "Optics Temp", value: "68", baseline: "58", unit: "°C", isNominal: false },
    ],
    sparklineHistory: [25, 28, 35, 42, 49, 55, 60, 58],
    predictedImpact: "Micro-porosity may surface at St.08 primer inspection",
    nextMaintenance: "In 14 hrs (Urgent focal calibration)",
    upstreamIds: [1, 2],
    downstreamIds: [4, 5],
  },
  {
    id: 4,
    stationNumber: 4,
    name: "Closure Panels Fitting",
    code: "ST-04-CP",
    zone: "Body Construction",
    orbitRing: 1,
    health: "online",
    instrumentation: "Partial",
    instrumentationDetails: "Partial — Gap & Flush 3D Optical Gauges",
    description: "Articulated lift arms mount hood, trunk, and door assemblies with optical gap calibration.",
    riskScore: 26,
    sensors: [
      { name: "Panel Flush", value: "3.2", baseline: "3.2", unit: "mm", isNominal: true },
      { name: "Gap Variance", value: "0.04", baseline: "0.05", unit: "mm", isNominal: true },
    ],
    sparklineHistory: [22, 24, 25, 27, 26, 25, 27, 26],
    predictedImpact: "Gap consistency within Class-A tolerance",
    nextMaintenance: "In 120 hrs (Routine calibration)",
    upstreamIds: [2, 3],
    downstreamIds: [5, 6],
  },
  {
    id: 5,
    stationNumber: 5,
    name: "Body-in-White 3D QA",
    code: "ST-05-QA",
    zone: "Body Construction",
    orbitRing: 1,
    health: "online",
    instrumentation: "Full",
    instrumentationDetails: "Full — Multi-Axis LiDAR, Vision Triangulation",
    description: "Dual LiDAR towers execute 100% volumetric coordinate scan of 4,200 critical body geometry points.",
    riskScore: 9,
    sensors: [
      { name: "Point Precision", value: "99.8", baseline: "99.5", unit: "%", isNominal: true },
      { name: "Scan Duration", value: "42", baseline: "45", unit: "sec", isNominal: true },
    ],
    sparklineHistory: [12, 10, 9, 11, 8, 9, 10, 9],
    predictedImpact: "Body geometry passed 100% geometry audit",
    nextMaintenance: "In 180 hrs (LiDAR cleaning)",
    upstreamIds: [3, 4],
    downstreamIds: [6, 7],
  },
  {
    id: 6,
    stationNumber: 6,
    name: "Paint Transfer Buffer",
    code: "ST-06-TR",
    zone: "Body Construction",
    orbitRing: 1,
    health: "online",
    instrumentation: "Manual",
    instrumentationDetails: "Manual — Operator Safety & Transit Log",
    description: "Automated skid carrier switches unpainted body shells into the sealed paint shop airlock.",
    riskScore: 18,
    manualLog: "Operator Alvarez: Airlock seal intact, skid rollers lubricated at 18:30 shift change.",
    predictedImpact: "Buffer throughput aligned with Paint Zone intake",
    nextMaintenance: "In 48 hrs (Conveyor roller check)",
    upstreamIds: [4, 5],
    downstreamIds: [7],
  },

  // MIDDLE RING (2): Paint Zone (7 Stations, ST-07 to ST-13)
  {
    id: 7,
    stationNumber: 7,
    name: "E-Coat Dip & Pre-Treat",
    code: "ST-07-EC",
    zone: "Paint",
    orbitRing: 2,
    health: "online",
    instrumentation: "Full",
    instrumentationDetails: "Full — Bath Conductivity, pH, Current Density",
    description: "Immersion tank provides cathodic electrodeposition anti-corrosion barrier across all crevices.",
    riskScore: 16,
    sensors: [
      { name: "Bath pH", value: "5.8", baseline: "5.8", unit: "pH", isNominal: true },
      { name: "Current Density", value: "1.4", baseline: "1.4", unit: "A/dm²", isNominal: true },
      { name: "Bath Temp", value: "28.5", baseline: "28.0", unit: "°C", isNominal: true },
    ],
    sparklineHistory: [14, 15, 16, 15, 17, 16, 15, 16],
    predictedImpact: "Film thickness uniform at 18.5µm target",
    nextMaintenance: "In 64 hrs (Anode cell flush)",
    upstreamIds: [5, 6],
    downstreamIds: [8],
  },
  {
    id: 8,
    stationNumber: 8,
    name: "PVC Seam Sealer Bot",
    code: "ST-08-SL",
    zone: "Paint",
    orbitRing: 2,
    health: "warning",
    instrumentation: "Full",
    instrumentationDetails: "Full — Nozzle Flow, Bead Height, Viscosity",
    description: "Robotic extruder applies sound-deadening and anti-water PVC bead along interior joints.",
    riskScore: 54,
    sensors: [
      { name: "Nozzle Flow", value: "48", baseline: "55", unit: "cc/s", isNominal: false },
      { name: "Bead Height", value: "2.1", baseline: "2.5", unit: "mm", isNominal: false },
    ],
    sparklineHistory: [28, 30, 36, 42, 48, 52, 56, 54],
    predictedImpact: "Thin acoustic bead may increase cabin NVH at St.19 test",
    nextMaintenance: "In 16 hrs (Nozzle head replacement)",
    upstreamIds: [7],
    downstreamIds: [9, 10],
  },
  {
    id: 9,
    stationNumber: 9,
    name: "Primer Surfacer Robot",
    code: "ST-09-PR",
    zone: "Paint",
    orbitRing: 2,
    health: "online",
    instrumentation: "Full",
    instrumentationDetails: "Full — Atomizer Bell Speed, Electrostatic KV",
    description: "High-rotation electrostatic bells atomize primer layer for stone-chip protection.",
    riskScore: 21,
    sensors: [
      { name: "Bell Speed", value: "48,000", baseline: "50,000", unit: "rpm", isNominal: true },
      { name: "Charging KV", value: "68", baseline: "70", unit: "kV", isNominal: true },
    ],
    sparklineHistory: [18, 19, 21, 23, 20, 22, 21, 21],
    predictedImpact: "Transfer efficiency 94.2% nominal",
    nextMaintenance: "In 80 hrs (Bell cup inspection)",
    upstreamIds: [8],
    downstreamIds: [10, 11],
  },
  {
    id: 10,
    stationNumber: 10,
    name: "Automated Basecoat Booth",
    code: "ST-10-BC",
    zone: "Paint",
    orbitRing: 2,
    health: "critical",
    instrumentation: "Full",
    instrumentationDetails: "Full — Fluid Flow, Spray Humidity, Color Index",
    description: "Synchronized dual-side robotic bells apply customer pigment coat with metallic flake orientation.",
    riskScore: 84,
    sensors: [
      { name: "Fluid Flow Rate", value: "310", baseline: "260", unit: "cc/min", isNominal: false },
      { name: "Booth Humidity", value: "78", baseline: "65", unit: "%", isNominal: false },
      { name: "Flake Index", value: "ΔE 1.8", baseline: "ΔE <0.5", unit: "CIELAB", isNominal: false },
    ],
    sparklineHistory: [38, 45, 58, 68, 74, 82, 86, 84],
    predictedImpact: "Color shade variance and solvent pop predicted at St.13 final inspection",
    nextMaintenance: "IMMEDIATE — Recalibrate fluid regulator & airflow damper",
    upstreamIds: [8, 9],
    downstreamIds: [11, 12],
  },
  {
    id: 11,
    stationNumber: 11,
    name: "Clearcoat & High Gloss",
    code: "ST-11-CC",
    zone: "Paint",
    orbitRing: 2,
    health: "online",
    instrumentation: "Full",
    instrumentationDetails: "Full — Viscosity, 2K Mixing Ratio, Electrostatic",
    description: "Two-component protective polyurethane clearcoat seals paint with 90+ high-gloss DOI finish.",
    riskScore: 19,
    sensors: [
      { name: "2K Ratio", value: "3.98:1", baseline: "4.00:1", unit: "Ratio", isNominal: true },
      { name: "DOI Gloss", value: "92.4", baseline: "90.0", unit: "Gloss", isNominal: true },
    ],
    sparklineHistory: [16, 17, 18, 20, 19, 19, 18, 19],
    predictedImpact: "Gloss index exceeds premium aesthetic threshold",
    nextMaintenance: "In 90 hrs (Filter cartridge change)",
    upstreamIds: [9, 10],
    downstreamIds: [12, 13],
  },
  {
    id: 12,
    stationNumber: 12,
    name: "Infrared Curing Oven",
    code: "ST-12-OV",
    zone: "Paint",
    orbitRing: 2,
    health: "online",
    instrumentation: "Full",
    instrumentationDetails: "Full — Zone Temp 1-4, Air Velocity, Exhaust",
    description: "4-stage convection and infrared tunnel bakes cross-linking polymers at 145°C holding curve.",
    riskScore: 28,
    sensors: [
      { name: "Zone 2 Temp", value: "146.2", baseline: "145.0", unit: "°C", isNominal: true },
      { name: "Airflow", value: "2.8", baseline: "3.0", unit: "m/s", isNominal: true },
    ],
    sparklineHistory: [24, 25, 28, 27, 29, 28, 27, 28],
    predictedImpact: "Polymer cure hardness verified at 2H rating",
    nextMaintenance: "In 110 hrs (Blower bearing check)",
    upstreamIds: [10, 11],
    downstreamIds: [13],
  },
  {
    id: 13,
    stationNumber: 13,
    name: "Automated Defect Optical Scan",
    code: "ST-13-SC",
    zone: "Paint",
    orbitRing: 2,
    health: "online",
    instrumentation: "Full",
    instrumentationDetails: "Full — Deflectometry Array, AI Vision Classifier",
    description: "Reflected zebra-pattern light array maps orange peel, dust inclusions, and micro-scratches.",
    riskScore: 12,
    sensors: [
      { name: "Defect Count", value: "1", baseline: "<3", unit: "per body", isNominal: true },
      { name: "Scan Velocity", value: "1.1", baseline: "1.2", unit: "m/s", isNominal: true },
    ],
    sparklineHistory: [14, 15, 12, 11, 13, 12, 11, 12],
    predictedImpact: "Cleared paint quality gate for Final Assembly transfer",
    nextMaintenance: "In 200 hrs (Deflectometry LED calibration)",
    upstreamIds: [11, 12],
    downstreamIds: [14],
  },

  // OUTER RING (3): Final Assembly (7 Stations, ST-14 to ST-20)
  {
    id: 14,
    stationNumber: 14,
    name: "Windshield Glass Cell",
    code: "ST-14-GL",
    zone: "Final Assembly",
    orbitRing: 3,
    health: "online",
    instrumentation: "Partial",
    instrumentationDetails: "Partial — Urethane Bead Dispenser & Vision Guide",
    description: "Vision-guided heavy arm applies primer and adhesive bead before pressing laminated glass.",
    riskScore: 19,
    sensors: [
      { name: "Urethane Bead", value: "9.8", baseline: "10.0", unit: "mm", isNominal: true },
      { name: "Insertion Force", value: "320", baseline: "300", unit: "N", isNominal: true },
    ],
    sparklineHistory: [16, 17, 19, 21, 18, 20, 19, 19],
    predictedImpact: "Windshield acoustic seal verified leak-proof",
    nextMaintenance: "In 84 hrs (Suction cup replacement)",
    upstreamIds: [13],
    downstreamIds: [15],
  },
  {
    id: 15,
    stationNumber: 15,
    name: "Cockpit & IP Marriage",
    code: "ST-15-IP",
    zone: "Final Assembly",
    orbitRing: 3,
    health: "online",
    instrumentation: "Full",
    instrumentationDetails: "Full — Multi-Spindle Torquing, Bus Telemetry",
    description: "Pre-assembled instrument panel and head-up display hoisted through door opening and locked.",
    riskScore: 23,
    sensors: [
      { name: "Bolt Torque", value: "38.4", baseline: "38.0", unit: "Nm", isNominal: true },
      { name: "CAN Bus Ping", value: "2.4", baseline: "<5.0", unit: "ms", isNominal: true },
    ],
    sparklineHistory: [20, 22, 24, 25, 23, 24, 23, 23],
    predictedImpact: "Instrument harness continuity passed automated test",
    nextMaintenance: "In 130 hrs (Torque calibration)",
    upstreamIds: [14],
    downstreamIds: [16],
  },
  {
    id: 16,
    stationNumber: 16,
    name: "Powertrain Chassis Marriage",
    code: "ST-16-PW",
    zone: "Final Assembly",
    orbitRing: 3,
    health: "warning",
    instrumentation: "Full",
    instrumentationDetails: "Full — 16-Spindle Smart Nutrunners, Lift Pressure",
    description: "Heavy AGV lifts front/rear subframes and e-drive powertrain to torque 16 primary chassis bolts.",
    riskScore: 62,
    sensors: [
      { name: "Spindle #7 Angle", value: "88.4", baseline: "90.0", unit: "deg", isNominal: false },
      { name: "Yield Torque", value: "172", baseline: "185", unit: "Nm", isNominal: false },
    ],
    sparklineHistory: [32, 38, 45, 52, 58, 64, 60, 62],
    predictedImpact: "Torque variance may surface at St.19 dynamic roller test",
    nextMaintenance: "In 8 hrs (Spindle #7 motor encoder service)",
    upstreamIds: [15],
    downstreamIds: [17, 18],
  },
  {
    id: 17,
    stationNumber: 17,
    name: "High-Voltage Battery Pack",
    code: "ST-17-HV",
    zone: "Final Assembly",
    orbitRing: 3,
    health: "online",
    instrumentation: "Full",
    instrumentationDetails: "Full — Insulation Resistance, Thermal Paste Scan",
    description: "Automated guided carrier docks 800V lithium pack under floorpan with pneumatic compression seals.",
    riskScore: 15,
    sensors: [
      { name: "Insulation R", value: "540", baseline: ">500", unit: "MΩ", isNominal: true },
      { name: "Coolant Seal ΔP", value: "0.02", baseline: "<0.05", unit: "bar", isNominal: true },
    ],
    sparklineHistory: [14, 15, 14, 16, 15, 14, 16, 15],
    predictedImpact: "HV containment isolation certified safe",
    nextMaintenance: "In 150 hrs (Paste nozzle purge)",
    upstreamIds: [16],
    downstreamIds: [18],
  },
  {
    id: 18,
    stationNumber: 18,
    name: "Interior Trim & Seats",
    code: "ST-18-TR",
    zone: "Final Assembly",
    orbitRing: 3,
    health: "online",
    instrumentation: "Manual",
    instrumentationDetails: "Manual — Operator Safety Clip Verification",
    description: "Ergonomic manipulator inserts seat modules; operator secures harness connections and seatbelt anchors.",
    riskScore: 20,
    manualLog: "Operator Jensen: Airbag squib clip and belt anchor click verified on VIN #4082 at 19:15.",
    predictedImpact: "Safety squib connectors locked and logged",
    nextMaintenance: "In 72 hrs (Manipulator hoist check)",
    upstreamIds: [16, 17],
    downstreamIds: [19],
  },
  {
    id: 19,
    stationNumber: 19,
    name: "End-of-Line Dyno & ADAS",
    code: "ST-19-DY",
    zone: "Final Assembly",
    orbitRing: 3,
    health: "online",
    instrumentation: "Full",
    instrumentationDetails: "Full — Dyno Rollers, Radar Calibration, Exhaust",
    description: "Vehicle driven onto roller bench to verify regenerative braking, ABS, radar alignment, and 0-100 acceleration.",
    riskScore: 27,
    sensors: [
      { name: "Brake Balance", value: "51/49", baseline: "50/50", unit: "Ratio", isNominal: true },
      { name: "Radar Yaw Offset", value: "0.04", baseline: "<0.10", unit: "deg", isNominal: true },
    ],
    sparklineHistory: [25, 28, 29, 27, 26, 28, 27, 27],
    predictedImpact: "Dynamic chassis and safety ADAS passed calibration",
    nextMaintenance: "In 60 hrs (Roller load cell check)",
    upstreamIds: [17, 18],
    downstreamIds: [20],
  },
  {
    id: 20,
    stationNumber: 20,
    name: "Water Ingress & Final Sign-Off",
    code: "ST-20-SO",
    zone: "Final Assembly",
    orbitRing: 3,
    health: "online",
    instrumentation: "Full",
    instrumentationDetails: "Full — High-Pressure Monsoon Chamber, RFID",
    description: "High-pressure deluge arch tests seals followed by automated digital certificate signing and dispatch gate clearance.",
    riskScore: 8,
    sensors: [
      { name: "Chamber Pressure", value: "3.8", baseline: "3.5", unit: "bar", isNominal: true },
      { name: "Ingress Sensors", value: "0", baseline: "0", unit: "detections", isNominal: true },
    ],
    sparklineHistory: [10, 9, 8, 9, 8, 7, 8, 8],
    predictedImpact: "Full digital birth certificate issued. Outbound logistics ready.",
    nextMaintenance: "In 200 hrs (Nozzle descaling)",
    upstreamIds: [19],
    downstreamIds: [],
  },
];export const defaultStations = productionStations;
